"""
Camouflage Pattern Generator for KiCad PCB Editor.
Generates automotive prototype style dazzle and swirl camouflage patterns
on silkscreen layers while automatically clipping away component pads.
"""

import math
import random
import pcbnew

# Safe layer ID definitions across KiCad versions (F_SilkS, B_SilkS)
LAYER_F_SILK = getattr(pcbnew, "F_SilkS", getattr(pcbnew, "F_Silkscreen", 37))
LAYER_B_SILK = getattr(pcbnew, "B_SilkS", getattr(pcbnew, "B_Silkscreen", 36))

# Marker string to identify shapes generated by this plugin
CAMO_SHAPE_MARKER = "CAMO_SILK_PLUGIN"


def get_item_uuid(item):
    """Safely get string representation of UUID from a KiCad board item."""
    if hasattr(item, "m_Uuid"):
        return item.m_Uuid.AsString()
    elif hasattr(item, "GetUuid"):
        return item.GetUuid().AsString()
    return ""


def make_line_chain(points):
    """
    Create a closed SHAPE_LINE_CHAIN from a list of (x, y) tuples or VECTOR2I points.
    Accepts floats in mm or VECTOR2I objects in internal units.
    """
    chain = pcbnew.SHAPE_LINE_CHAIN()
    for pt in points:
        if isinstance(pt, pcbnew.VECTOR2I):
            chain.Append(pt)
        elif hasattr(pt, "x") and hasattr(pt, "y"):
            chain.Append(pcbnew.VECTOR2I(int(pt.x), int(pt.y)))
        else:
            chain.Append(pcbnew.VECTOR2I(int(pt[0] * 1e6), int(pt[1] * 1e6)))
    chain.SetClosed(True)
    return chain


def safe_inflate(poly_set, amount_nm, max_error_nm=10000):
    """
    Inflate a SHAPE_POLY_SET accommodating KiCad 7, 8, and 9 API signatures.
    """
    if poly_set.OutlineCount() == 0 or amount_nm <= 0:
        return

    # Find corner strategy enum if available
    strategy = 0
    for strat_name in ("ROUND", "CHAMFER_ALL_CORNERS", "CHAMFER_ACUTE_CORNERS"):
        if hasattr(pcbnew.SHAPE_POLY_SET, strat_name):
            strategy = getattr(pcbnew.SHAPE_POLY_SET, strat_name)
            break

    for args in [
        (amount_nm, strategy, max_error_nm),          # KiCad 9 (amount, strategy, max_error)
        (amount_nm, strategy, max_error_nm, False),   # KiCad 9 (amount, strategy, max_error, simplify)
        (amount_nm, max_error_nm),                   # KiCad 8 / 7 (amount, max_error)
        (amount_nm, 16),                             # KiCad legacy (amount, segments)
        (amount_nm,),                                # Fallback 1-arg
    ]:
        try:
            poly_set.Inflate(*args)
            return
        except TypeError:
            continue


class CamoGenerator:
    """Generates silkscreen camouflage patterns with automatic pad avoidance."""

    def __init__(self, board):
        self.board = board

    def get_board_bounds(self, margin_mm=0.5):
        """
        Get the bounding box of the board outline with an inner margin.
        Returns (x_min_mm, y_min_mm, x_max_mm, y_max_mm).
        """
        bbox = self.board.GetBoardEdgesBoundingBox()
        if bbox.GetWidth() <= 0 or bbox.GetHeight() <= 0:
            # Fallback to general bounding box
            bbox = self.board.ComputeBoundingBox()

        x_min = bbox.GetX() / 1e6 + margin_mm
        y_min = bbox.GetY() / 1e6 + margin_mm
        x_max = (bbox.GetX() + bbox.GetWidth()) / 1e6 - margin_mm
        y_max = (bbox.GetY() + bbox.GetHeight()) / 1e6 - margin_mm

        # Ensure valid area
        if x_max <= x_min or y_max <= y_min:
            x_min = bbox.GetX() / 1e6
            y_min = bbox.GetY() / 1e6
            x_max = (bbox.GetX() + bbox.GetWidth()) / 1e6
            y_max = (bbox.GetY() + bbox.GetHeight()) / 1e6

        return x_min, y_min, x_max, y_max

    def build_pad_keepout_polyset(self, side="F", clearance_mm=0.4):
        """
        Build a SHAPE_POLY_SET containing all pads on the target side,
        expanded by the given clearance.
        """
        keepout = pcbnew.SHAPE_POLY_SET()
        copper_layer = pcbnew.F_Cu if side == "F" else pcbnew.B_Cu
        clearance_nm = int(clearance_mm * 1e6)

        for fp in self.board.GetFootprints():
            for pad in fp.Pads():
                # Check if pad is on this copper layer or is a through-hole pad
                if pad.IsOnLayer(copper_layer):
                    # Get effective shape polygon
                    try:
                        pad_poly = pad.GetEffectivePolygon()
                        for oi in range(pad_poly.OutlineCount()):
                            keepout.AddOutline(pad_poly.Outline(oi))
                            for hi in range(pad_poly.HoleCount(oi)):
                                keepout.AddHole(pad_poly.Hole(oi, hi))
                    except Exception:
                        # Fallback: create bounding box polygon
                        p_bbox = pad.GetBoundingBox()
                        rect_poly = pcbnew.SHAPE_POLY_SET()
                        rect_poly.AddOutline(make_line_chain([
                            pcbnew.VECTOR2I(p_bbox.GetX(), p_bbox.GetY()),
                            pcbnew.VECTOR2I(p_bbox.GetRight(), p_bbox.GetY()),
                            pcbnew.VECTOR2I(p_bbox.GetRight(), p_bbox.GetBottom()),
                            pcbnew.VECTOR2I(p_bbox.GetX(), p_bbox.GetBottom())
                        ]))
                        keepout.AddOutline(rect_poly.Outline(0))

        # Simplify collected pad outlines
        try:
            keepout.Simplify()
        except Exception:
            pass

        # Inflate all pads by clearance
        if clearance_nm > 0 and keepout.OutlineCount() > 0:
            safe_inflate(keepout, clearance_nm)

        return keepout

    def build_silk_keepout_polyset(self, side="F", clearance_mm=0.3):
        """
        Build a SHAPE_POLY_SET containing keepouts for existing silkscreen markings
        (footprint polarity marks, pin 1 markers, diode cathode bars, icons, texts)
        to prevent camouflage from drawing over them.
        """
        silk_keepout = pcbnew.SHAPE_POLY_SET()
        target_layer = LAYER_F_SILK if side == "F" else LAYER_B_SILK
        clearance_nm = int(clearance_mm * 1e6)

        # 1. Footprint silkscreen graphical items (pin 1 dots, diode markings, outlines)
        for fp in self.board.GetFootprints():
            try:
                for item in fp.GraphicalItems():
                    if item.GetLayer() == target_layer:
                        item_poly = pcbnew.SHAPE_POLY_SET()
                        success = False

                        # Try native TransformShapeToPolygon (extracts stroked lines, arcs, unfilled rects)
                        try:
                            item.TransformShapeToPolygon(item_poly, clearance_nm, 10000)
                            if item_poly.OutlineCount() > 0:
                                success = True
                        except Exception:
                            try:
                                item.TransformShapeToPolygon(item_poly, clearance_nm)
                                if item_poly.OutlineCount() > 0:
                                    success = True
                            except Exception:
                                pass

                        # Precise geometric fallback for line segments and circles
                        if not success:
                            try:
                                shape_type = item.GetShape() if hasattr(item, "GetShape") else None
                                if shape_type == pcbnew.SHAPE_T_SEGMENT:
                                    p1 = item.GetStart()
                                    p2 = item.GetEnd()
                                    w = (item.GetWidth() or int(0.15 * 1e6)) + 2 * clearance_nm
                                    dx = p2.x - p1.x
                                    dy = p2.y - p1.y
                                    dist = math.hypot(dx, dy)
                                    if dist > 0:
                                        half_w = w / 2.0
                                        nx = -dy / dist * half_w
                                        ny = dx / dist * half_w
                                        ex = dx / dist * clearance_nm
                                        ey = dy / dist * clearance_nm
                                        seg_pts = [
                                            pcbnew.VECTOR2I(int(p1.x - ex + nx), int(p1.y - ey + ny)),
                                            pcbnew.VECTOR2I(int(p2.x + ex + nx), int(p2.y + ey + ny)),
                                            pcbnew.VECTOR2I(int(p2.x + ex - nx), int(p2.y + ey - ny)),
                                            pcbnew.VECTOR2I(int(p1.x - ex - nx), int(p1.y - ey - ny)),
                                        ]
                                        item_poly.AddOutline(make_line_chain(seg_pts))
                                        success = True
                                elif shape_type == pcbnew.SHAPE_T_CIRCLE:
                                    center = item.GetCenter()
                                    r = (item.GetRadius() if hasattr(item, "GetRadius") else 0) + clearance_nm
                                    if r > 0:
                                        circ_pts = []
                                        for a_idx in range(16):
                                            ang = 2.0 * math.pi * a_idx / 16.0
                                            circ_pts.append(pcbnew.VECTOR2I(
                                                int(center.x + r * math.cos(ang)),
                                                int(center.y + r * math.sin(ang))
                                            ))
                                        item_poly.AddOutline(make_line_chain(circ_pts))
                                        success = True
                                elif shape_type == pcbnew.SHAPE_T_POLY or hasattr(item, "GetPolyShape"):
                                    # 1-pin triangles (▶), arrows, custom silk polygon markings
                                    poly = item.GetPolyShape()
                                    if poly and poly.OutlineCount() > 0:
                                        copy_poly = pcbnew.SHAPE_POLY_SET(poly)
                                        safe_inflate(copy_poly, clearance_nm)
                                        for oi in range(copy_poly.OutlineCount()):
                                            item_poly.AddOutline(copy_poly.Outline(oi))
                                            for hi in range(copy_poly.HoleCount(oi)):
                                                item_poly.AddHole(copy_poly.Hole(oi, hi))
                                        success = True
                                elif shape_type == pcbnew.SHAPE_T_ARC:
                                    try:
                                        arc_poly = pcbnew.SHAPE_POLY_SET()
                                        item.TransformShapeToPolygon(arc_poly, clearance_nm, 10000)
                                        if arc_poly.OutlineCount() > 0:
                                            for oi in range(arc_poly.OutlineCount()):
                                                item_poly.AddOutline(arc_poly.Outline(oi))
                                            success = True
                                    except Exception:
                                        pass

                                # Small mark fallback (< 3mm) to guarantee protection of any unknown tiny symbols
                                if not success:
                                    bbox = item.GetBoundingBox()
                                    w_mm = bbox.GetWidth() / 1e6
                                    h_mm = bbox.GetHeight() / 1e6
                                    if 0 < w_mm < 3.0 and 0 < h_mm < 3.0:
                                        rect_pts = [
                                            pcbnew.VECTOR2I(bbox.GetX() - clearance_nm, bbox.GetY() - clearance_nm),
                                            pcbnew.VECTOR2I(bbox.GetRight() + clearance_nm, bbox.GetY() - clearance_nm),
                                            pcbnew.VECTOR2I(bbox.GetRight() + clearance_nm, bbox.GetBottom() + clearance_nm),
                                            pcbnew.VECTOR2I(bbox.GetX() - clearance_nm, bbox.GetBottom() + clearance_nm),
                                        ]
                                        item_poly.AddOutline(make_line_chain(rect_pts))
                                        success = True
                            except Exception:
                                pass

                        if success:
                            for oi in range(item_poly.OutlineCount()):
                                silk_keepout.AddOutline(item_poly.Outline(oi))
                                for hi in range(item_poly.HoleCount(oi)):
                                    silk_keepout.AddHole(item_poly.Hole(oi, hi))
            except Exception:
                pass

            # 2. Footprint visible silkscreen texts (pin names, polarity labels)
            try:
                for txt_item in (fp.Reference(), fp.Value()):
                    if txt_item and txt_item.GetLayer() == target_layer and txt_item.IsVisible():
                        bbox = txt_item.GetBoundingBox()
                        if bbox.GetWidth() > 0 and bbox.GetHeight() > 0:
                            rect_poly = pcbnew.SHAPE_POLY_SET()
                            rect_poly.AddOutline(make_line_chain([
                                pcbnew.VECTOR2I(bbox.GetX(), bbox.GetY()),
                                pcbnew.VECTOR2I(bbox.GetRight(), bbox.GetY()),
                                pcbnew.VECTOR2I(bbox.GetRight(), bbox.GetBottom()),
                                pcbnew.VECTOR2I(bbox.GetX(), bbox.GetBottom())
                            ]))
                            silk_keepout.AddOutline(rect_poly.Outline(0))
            except Exception:
                pass

        # 3. Simplify collected silk keepout outlines
        try:
            silk_keepout.Simplify()
        except Exception:
            pass

        return silk_keepout

    def generate_swirl_polygons(self, bounds, scale_mm=10.0, line_width_mm=0.8, seed=42):
        """
        Generate automotive test mule swirl (spiral / vortex) ribbon polygons.
        Fully randomizes vortex center positions, starting rotation angles, pitch, and directions.
        """
        random.seed(seed)
        x_min, y_min, x_max, y_max = bounds
        width = x_max - x_min
        height = y_max - y_min

        poly_set = pcbnew.SHAPE_POLY_SET()

        # Distribute vortex centers with random positions and density
        area = max(1.0, width * height)
        cell_area = max(4.0, scale_mm * scale_mm)
        num_centers = max(2, int(area / cell_area) + random.randint(1, 3))

        centers = []
        # Mix jittered grid and scatter for natural organic distribution
        cols = max(1, int(width / scale_mm))
        rows = max(1, int(height / scale_mm))

        for r in range(rows + 1):
            for c in range(cols + 1):
                # Generous jitter around cell to avoid rigid grid alignment
                cx = x_min + (c + random.uniform(-0.6, 0.6)) * scale_mm
                cy = y_min + (r + random.uniform(-0.6, 0.6)) * scale_mm
                direction = random.choice([-1, 1])
                rot_offset = random.uniform(0, 2.0 * math.pi)
                pitch_mult = random.uniform(0.75, 1.25)
                arm_count = random.choice([2, 3])
                max_radius = scale_mm * random.uniform(1.2, 2.0)
                centers.append((cx, cy, direction, rot_offset, pitch_mult, arm_count, max_radius))

        # Generate spiral arms from each center
        for cx, cy, direction, rot_offset, pitch_mult, num_arms, max_r in centers:
            half_w = (line_width_mm * random.uniform(0.9, 1.1)) / 2.0

            for arm in range(num_arms):
                base_angle = rot_offset + (2.0 * math.pi / num_arms) * arm
                points_outer = []
                points_inner = []

                # Trace spiral: r = b * theta
                b = ((scale_mm / 2.0) / (2.0 * math.pi)) * pitch_mult
                steps = max(25, int(50 * (max_r / (scale_mm * 1.5))))

                for s in range(4, steps):
                    theta = s * 0.14
                    r = b * theta
                    if r > max_r:
                        break

                    angle = base_angle + direction * theta
                    # Midline point
                    mx = cx + r * math.cos(angle)
                    my = cy + r * math.sin(angle)

                    # Perpendicular offset for ribbon thickness
                    perp_angle = angle + math.pi / 2.0
                    dx = half_w * math.cos(perp_angle)
                    dy = half_w * math.sin(perp_angle)

                    points_outer.append((mx + dx, my + dy))
                    points_inner.append((mx - dx, my - dy))

                if len(points_outer) >= 3:
                    # Form closed ribbon polygon
                    polygon_pts = points_outer + list(reversed(points_inner))
                    poly_set.AddOutline(make_line_chain(polygon_pts))

        return poly_set

    def generate_dazzle_polygons(self, bounds, scale_mm=8.0, seed=42):
        """
        Generate geometric dazzle camouflage (angled alternating polygonal blocks).
        """
        random.seed(seed)
        x_min, y_min, x_max, y_max = bounds
        width = x_max - x_min
        height = y_max - y_min

        poly_set = pcbnew.SHAPE_POLY_SET()

        angles = [math.radians(30), math.radians(45), math.radians(60),
                  math.radians(120), math.radians(135), math.radians(150)]

        # Divide into grid cells with random angled stripes in each
        cell_size = scale_mm * 1.5
        cols = max(1, int(width / cell_size) + 1)
        rows = max(1, int(height / cell_size) + 1)

        for r in range(rows):
            for c in range(cols):
                bx0 = x_min + c * cell_size
                by0 = y_min + r * cell_size
                bx1 = min(x_max, bx0 + cell_size)
                by1 = min(y_max, by0 + cell_size)

                angle = random.choice(angles)
                stripe_w = scale_mm * random.uniform(0.3, 0.6)

                # Generate angled strips within this bounding cell
                cos_a = math.cos(angle)
                sin_a = math.sin(angle)

                diag = math.hypot(cell_size, cell_size)
                num_stripes = int(diag / (stripe_w * 2)) + 2

                cx = (bx0 + bx1) / 2.0
                cy = (by0 + by1) / 2.0

                for i in range(-num_stripes, num_stripes, 2):
                    offset = i * stripe_w
                    # Strip center line offset along normal
                    nx = -sin_a
                    ny = cos_a

                    p1x = cx + offset * nx - diag * cos_a
                    p1y = cy + offset * ny - diag * sin_a
                    p2x = cx + offset * nx + diag * cos_a
                    p2y = cy + offset * ny + diag * sin_a

                    # Extrude by stripe_w
                    half = stripe_w / 2.0
                    strip_pts = [
                        (p1x - half * nx, p1y - half * ny),
                        (p2x - half * nx, p2y - half * ny),
                        (p2x + half * nx, p2y + half * ny),
                        (p1x + half * nx, p1y + half * ny)
                    ]

                    strip_poly = pcbnew.SHAPE_POLY_SET()
                    strip_poly.AddOutline(make_line_chain(strip_pts))

                    # Intersect with cell box
                    cell_poly = pcbnew.SHAPE_POLY_SET()
                    cell_poly.AddOutline(make_line_chain([
                        (bx0, by0),
                        (bx1, by0),
                        (bx1, by1),
                        (bx0, by1)
                    ]))

                    strip_poly.BooleanIntersection(cell_poly)
                    for oi in range(strip_poly.OutlineCount()):
                        poly_set.AddOutline(strip_poly.Outline(oi))

        return poly_set

    def generate_zebra_polygons(self, bounds, scale_mm=8.0, line_width_mm=0.8, seed=42):
        """
        Generate organic undulating zebra waves.
        """
        random.seed(seed)
        x_min, y_min, x_max, y_max = bounds
        height = y_max - y_min

        poly_set = pcbnew.SHAPE_POLY_SET()
        half_w = line_width_mm / 2.0

        num_stripes = max(2, int(height / scale_mm))
        step_y = height / num_stripes

        for i in range(num_stripes + 1):
            base_y = y_min + i * step_y
            freq1 = 2.0 * math.pi / (scale_mm * random.uniform(2.0, 4.0))
            freq2 = 2.0 * math.pi / (scale_mm * random.uniform(0.8, 1.5))
            amp1 = scale_mm * 0.25
            amp2 = scale_mm * 0.1
            phase1 = random.uniform(0, 2 * math.pi)
            phase2 = random.uniform(0, 2 * math.pi)

            pts_top = []
            pts_bot = []

            steps = max(10, int((x_max - x_min) / 0.5))
            dx = (x_max - x_min) / steps

            for s in range(steps + 1):
                x = x_min + s * dx
                wave = amp1 * math.sin(freq1 * x + phase1) + amp2 * math.sin(freq2 * x + phase2)
                my = base_y + wave

                pts_top.append((x, my - half_w))
                pts_bot.append((x, my + half_w))

            strip_pts = pts_top + list(reversed(pts_bot))
            poly_set.AddOutline(make_line_chain(strip_pts))

        return poly_set

    def generate_camouflage(self, side="F", pattern_type="swirl", scale_mm=8.0,
                            line_width_mm=0.8, pad_clearance_mm=0.4,
                            board_margin_mm=0.5, seed=42, existing_uuids=None):
        """
        Main entry point to generate camouflage shapes and add them to the board.
        If existing_uuids is provided, automatically merges the new layer with existing shapes.
        Returns (number of shapes added, list of created UUIDs).
        """
        target_layer = LAYER_F_SILK if side == "F" else LAYER_B_SILK
        bounds = self.get_board_bounds(margin_mm=board_margin_mm)

        # 1. Generate base camo poly set based on pattern type
        if pattern_type == "dazzle":
            camo_poly = self.generate_dazzle_polygons(bounds, scale_mm=scale_mm, seed=seed)
        elif pattern_type == "zebra":
            camo_poly = self.generate_zebra_polygons(bounds, scale_mm=scale_mm,
                                                     line_width_mm=line_width_mm, seed=seed)
        else:  # default: swirl
            camo_poly = self.generate_swirl_polygons(bounds, scale_mm=scale_mm,
                                                     line_width_mm=line_width_mm, seed=seed)

        # 2. If layering on top of existing camo, collect existing outlines to merge seamlessly
        existing_shapes = []
        if existing_uuids:
            uuid_set = set(existing_uuids)
            for drawing in self.board.GetDrawings():
                if drawing.GetLayer() == target_layer:
                    uid = get_item_uuid(drawing)
                    is_match = False
                    if uid and uid in uuid_set:
                        is_match = True
                    elif isinstance(drawing, pcbnew.PCB_SHAPE) and drawing.GetShape() == pcbnew.SHAPE_T_POLY and drawing.IsFilled():
                        is_match = True

                    if is_match:
                        existing_shapes.append(drawing)
                        poly = drawing.GetPolyShape()
                        for oi in range(poly.OutlineCount()):
                            camo_poly.AddOutline(poly.Outline(oi))
                            for hi in range(poly.HoleCount(oi)):
                                camo_poly.AddHole(poly.Hole(oi, hi))

        # Simplify polygon set to merge overlapping ribbons into unified shapes
        try:
            camo_poly.Simplify()
        except Exception:
            pass

        # 3. Clip with board boundary box
        x_min, y_min, x_max, y_max = bounds
        board_box = pcbnew.SHAPE_POLY_SET()
        board_box.AddOutline(make_line_chain([
            (x_min, y_min),
            (x_max, y_min),
            (x_max, y_max),
            (x_min, y_max)
        ]))
        camo_poly.BooleanIntersection(board_box)

        # 4. Build pad & silkscreen keepout and subtract
        keepout = self.build_pad_keepout_polyset(side=side, clearance_mm=pad_clearance_mm)
        silk_keepout = self.build_silk_keepout_polyset(side=side, clearance_mm=pad_clearance_mm)
        if silk_keepout.OutlineCount() > 0:
            for oi in range(silk_keepout.OutlineCount()):
                keepout.AddOutline(silk_keepout.Outline(oi))
                for hi in range(silk_keepout.HoleCount(oi)):
                    keepout.AddHole(silk_keepout.Hole(oi, hi))

        if keepout.OutlineCount() > 0:
            camo_poly.BooleanSubtract(keepout)

        # 5. Remove old existing shapes now that new unified poly set is ready
        for item in existing_shapes:
            try:
                self.board.Remove(item)
            except Exception:
                pass
            try:
                item.Delete()
            except Exception:
                pass

        # 6. Add resulting polygons to board as PCB_SHAPE
        count = 0
        created_uuids = []

        # Iterate through outlines in camo_poly
        for i in range(camo_poly.OutlineCount()):
            shape = pcbnew.PCB_SHAPE(self.board)
            shape.SetShape(pcbnew.SHAPE_T_POLY)
            shape.SetLayer(target_layer)
            shape.SetFilled(True)

            # Assign single polygon outline
            single_poly = pcbnew.SHAPE_POLY_SET()
            single_poly.AddOutline(camo_poly.Outline(i))
            
            # Add corresponding holes if any
            for h in range(camo_poly.HoleCount(i)):
                single_poly.AddHole(camo_poly.Hole(i, h))

            shape.SetPolyShape(single_poly)

            self.board.Add(shape)
            count += 1

            uid = get_item_uuid(shape)
            if uid:
                created_uuids.append(uid)

        pcbnew.Refresh()
        return count, created_uuids

    def remove_all_camo_shapes(self, side=None, target_uuids=None):
        """
        Remove camouflage shapes generated by this plugin.
        Matches by UUID or identifies filled SHAPE_T_POLY polygons on the target silkscreen layer.
        side: 'F', 'B', or None (both)
        target_uuids: Optional list/set of UUID strings previously generated
        Returns count of removed shapes.
        """
        layers = []
        if side in ("F", None):
            layers.append(LAYER_F_SILK)
        if side in ("B", None):
            layers.append(LAYER_B_SILK)

        uuid_set = set(target_uuids or [])
        to_delete = []

        for drawing in self.board.GetDrawings():
            if drawing.GetLayer() in layers:
                is_camo = False
                uid = get_item_uuid(drawing)

                # Match by explicit UUID
                if uid and uid in uuid_set:
                    is_camo = True

                # Fallback: identify by filled polygon (SHAPE_T_POLY) on silk layer
                if not is_camo and isinstance(drawing, pcbnew.PCB_SHAPE):
                    if drawing.GetShape() == pcbnew.SHAPE_T_POLY and drawing.IsFilled():
                        is_camo = True

                if is_camo:
                    to_delete.append(drawing)

        for item in to_delete:
            try:
                self.board.Remove(item)
            except Exception:
                pass
            try:
                item.Delete()
            except Exception:
                pass

        if to_delete:
            pcbnew.Refresh()

        return len(to_delete)
