"""
Camouflage Pattern Generator for KiCad PCB Editor.
Generates automotive prototype style dazzle and swirl camouflage patterns
on silkscreen layers while automatically clipping away component pads.
"""

import math
import random
import pcbnew

# Safe layer ID definitions across KiCad versions (F_SilkS, B_SilkS)
LAYER_F_SILK = getattr(pcbnew, "F_SilkS", getattr(pcbnew, "F_Silkscreen", 37))
LAYER_B_SILK = getattr(pcbnew, "B_SilkS", getattr(pcbnew, "B_Silkscreen", 36))

# Marker string to identify shapes generated by this plugin
CAMO_SHAPE_MARKER = "CAMO_SILK_PLUGIN"


def make_line_chain(points):
    """
    Create a closed SHAPE_LINE_CHAIN from a list of (x, y) tuples or VECTOR2I points.
    Accepts floats in mm or VECTOR2I objects in internal units.
    """
    chain = pcbnew.SHAPE_LINE_CHAIN()
    for pt in points:
        if isinstance(pt, pcbnew.VECTOR2I):
            chain.Append(pt)
        elif hasattr(pt, "x") and hasattr(pt, "y"):
            chain.Append(pcbnew.VECTOR2I(int(pt.x), int(pt.y)))
        else:
            chain.Append(pcbnew.VECTOR2I(int(pt[0] * 1e6), int(pt[1] * 1e6)))
    chain.SetClosed(True)
    return chain


class CamoGenerator:
    """Generates silkscreen camouflage patterns with automatic pad avoidance."""

    def __init__(self, board):
        self.board = board

    def get_board_bounds(self, margin_mm=0.5):
        """
        Get the bounding box of the board outline with an inner margin.
        Returns (x_min_mm, y_min_mm, x_max_mm, y_max_mm).
        """
        bbox = self.board.GetBoardEdgesBoundingBox()
        if bbox.GetWidth() <= 0 or bbox.GetHeight() <= 0:
            # Fallback to general bounding box
            bbox = self.board.ComputeBoundingBox()

        x_min = bbox.GetX() / 1e6 + margin_mm
        y_min = bbox.GetY() / 1e6 + margin_mm
        x_max = (bbox.GetX() + bbox.GetWidth()) / 1e6 - margin_mm
        y_max = (bbox.GetY() + bbox.GetHeight()) / 1e6 - margin_mm

        # Ensure valid area
        if x_max <= x_min or y_max <= y_min:
            x_min = bbox.GetX() / 1e6
            y_min = bbox.GetY() / 1e6
            x_max = (bbox.GetX() + bbox.GetWidth()) / 1e6
            y_max = (bbox.GetY() + bbox.GetHeight()) / 1e6

        return x_min, y_min, x_max, y_max

    def build_pad_keepout_polyset(self, side="F", clearance_mm=0.4):
        """
        Build a SHAPE_POLY_SET containing all pads on the target side,
        expanded by the given clearance.
        """
        keepout = pcbnew.SHAPE_POLY_SET()
        copper_layer = pcbnew.F_Cu if side == "F" else pcbnew.B_Cu
        clearance_nm = int(clearance_mm * 1e6)

        for fp in self.board.GetFootprints():
            for pad in fp.Pads():
                # Check if pad is on this copper layer or is a through-hole pad
                if pad.IsOnLayer(copper_layer):
                    # Get effective shape polygon
                    try:
                        pad_poly = pad.GetEffectivePolygon()
                        keepout.BooleanAdd(pad_poly, pcbnew.SHAPE_POLY_SET.PM_FAST)
                    except Exception:
                        # Fallback: create bounding box polygon
                        p_bbox = pad.GetBoundingBox()
                        rect_poly = pcbnew.SHAPE_POLY_SET()
                        rect_poly.AddOutline(make_line_chain([
                            pcbnew.VECTOR2I(p_bbox.GetX(), p_bbox.GetY()),
                            pcbnew.VECTOR2I(p_bbox.GetRight(), p_bbox.GetY()),
                            pcbnew.VECTOR2I(p_bbox.GetRight(), p_bbox.GetBottom()),
                            pcbnew.VECTOR2I(p_bbox.GetX(), p_bbox.GetBottom())
                        ]))
                        keepout.BooleanAdd(rect_poly, pcbnew.SHAPE_POLY_SET.PM_FAST)

        # Inflate all pads by clearance
        if clearance_nm > 0 and keepout.OutlineCount() > 0:
            keepout.Inflate(clearance_nm, 16)

        return keepout

    def generate_swirl_polygons(self, bounds, scale_mm=10.0, line_width_mm=0.8, seed=42):
        """
        Generate automotive test mule swirl (spiral / vortex) ribbon polygons.
        """
        random.seed(seed)
        x_min, y_min, x_max, y_max = bounds
        width = x_max - x_min
        height = y_max - y_min

        poly_set = pcbnew.SHAPE_POLY_SET()

        # Determine number of vortex centers based on scale
        cols = max(1, int(width / scale_mm))
        rows = max(1, int(height / scale_mm))
        centers = []

        for r in range(rows + 1):
            for c in range(cols + 1):
                cx = x_min + (c + random.uniform(-0.3, 0.3)) * scale_mm
                cy = y_min + (r + random.uniform(-0.3, 0.3)) * scale_mm
                direction = 1 if (r + c) % 2 == 0 else -1
                centers.append((cx, cy, direction))

        # Generate spiral arms from each center
        half_w = line_width_mm / 2.0
        max_r = scale_mm * 1.6

        for cx, cy, direction in centers:
            # 2 to 3 interleaved spiral arms
            num_arms = 2
            for arm in range(num_arms):
                base_angle = (2.0 * math.pi / num_arms) * arm
                points_outer = []
                points_inner = []

                # Trace spiral: r = b * theta
                steps = 40
                b = (scale_mm / 2.0) / (2.0 * math.pi)
                for s in range(5, steps):
                    theta = s * 0.15
                    r = b * theta
                    if r > max_r:
                        break

                    angle = base_angle + direction * theta
                    # Midline
                    mx = cx + r * math.cos(angle)
                    my = cy + r * math.sin(angle)

                    # Perpendicular vector for thickness
                    perp_angle = angle + math.pi / 2.0
                    dx = half_w * math.cos(perp_angle)
                    dy = half_w * math.sin(perp_angle)

                    points_outer.append((mx + dx, my + dy))
                    points_inner.append((mx - dx, my - dy))

                if len(points_outer) >= 3:
                    # Form closed ribbon polygon
                    polygon_pts = points_outer + list(reversed(points_inner))
                    outline = pcbnew.SHAPE_POLY_SET()
                    outline.AddOutline(make_line_chain(polygon_pts))
                    poly_set.BooleanAdd(outline, pcbnew.SHAPE_POLY_SET.PM_FAST)

        return poly_set

    def generate_dazzle_polygons(self, bounds, scale_mm=8.0, seed=42):
        """
        Generate geometric dazzle camouflage (angled alternating polygonal blocks).
        """
        random.seed(seed)
        x_min, y_min, x_max, y_max = bounds
        width = x_max - x_min
        height = y_max - y_min

        poly_set = pcbnew.SHAPE_POLY_SET()

        angles = [math.radians(30), math.radians(45), math.radians(60),
                  math.radians(120), math.radians(135), math.radians(150)]

        # Divide into grid cells with random angled stripes in each
        cell_size = scale_mm * 1.5
        cols = max(1, int(width / cell_size) + 1)
        rows = max(1, int(height / cell_size) + 1)

        for r in range(rows):
            for c in range(cols):
                bx0 = x_min + c * cell_size
                by0 = y_min + r * cell_size
                bx1 = min(x_max, bx0 + cell_size)
                by1 = min(y_max, by0 + cell_size)

                angle = random.choice(angles)
                stripe_w = scale_mm * random.uniform(0.3, 0.6)

                # Generate angled strips within this bounding cell
                cos_a = math.cos(angle)
                sin_a = math.sin(angle)

                diag = math.hypot(cell_size, cell_size)
                num_stripes = int(diag / (stripe_w * 2)) + 2

                cx = (bx0 + bx1) / 2.0
                cy = (by0 + by1) / 2.0

                for i in range(-num_stripes, num_stripes, 2):
                    offset = i * stripe_w
                    # Strip center line offset along normal
                    nx = -sin_a
                    ny = cos_a

                    p1x = cx + offset * nx - diag * cos_a
                    p1y = cy + offset * ny - diag * sin_a
                    p2x = cx + offset * nx + diag * cos_a
                    p2y = cy + offset * ny + diag * sin_a

                    # Extrude by stripe_w
                    half = stripe_w / 2.0
                    strip_pts = [
                        (p1x - half * nx, p1y - half * ny),
                        (p2x - half * nx, p2y - half * ny),
                        (p2x + half * nx, p2y + half * ny),
                        (p1x + half * nx, p1y + half * ny)
                    ]

                    strip_poly = pcbnew.SHAPE_POLY_SET()
                    strip_poly.AddOutline(make_line_chain(strip_pts))

                    # Intersect with cell box
                    cell_poly = pcbnew.SHAPE_POLY_SET()
                    cell_poly.AddOutline(make_line_chain([
                        (bx0, by0),
                        (bx1, by0),
                        (bx1, by1),
                        (bx0, by1)
                    ]))

                    strip_poly.BooleanIntersection(cell_poly, pcbnew.SHAPE_POLY_SET.PM_FAST)
                    if strip_poly.OutlineCount() > 0:
                        poly_set.BooleanAdd(strip_poly, pcbnew.SHAPE_POLY_SET.PM_FAST)

        return poly_set

    def generate_zebra_polygons(self, bounds, scale_mm=8.0, line_width_mm=0.8, seed=42):
        """
        Generate organic undulating zebra waves.
        """
        random.seed(seed)
        x_min, y_min, x_max, y_max = bounds
        height = y_max - y_min

        poly_set = pcbnew.SHAPE_POLY_SET()
        half_w = line_width_mm / 2.0

        num_stripes = max(2, int(height / scale_mm))
        step_y = height / num_stripes

        for i in range(num_stripes + 1):
            base_y = y_min + i * step_y
            freq1 = 2.0 * math.pi / (scale_mm * random.uniform(2.0, 4.0))
            freq2 = 2.0 * math.pi / (scale_mm * random.uniform(0.8, 1.5))
            amp1 = scale_mm * 0.25
            amp2 = scale_mm * 0.1
            phase1 = random.uniform(0, 2 * math.pi)
            phase2 = random.uniform(0, 2 * math.pi)

            pts_top = []
            pts_bot = []

            steps = max(10, int((x_max - x_min) / 0.5))
            dx = (x_max - x_min) / steps

            for s in range(steps + 1):
                x = x_min + s * dx
                wave = amp1 * math.sin(freq1 * x + phase1) + amp2 * math.sin(freq2 * x + phase2)
                my = base_y + wave

                pts_top.append((x, my - half_w))
                pts_bot.append((x, my + half_w))

            strip_pts = pts_top + list(reversed(pts_bot))
            outline = pcbnew.SHAPE_POLY_SET()
            outline.AddOutline(make_line_chain(strip_pts))
            poly_set.BooleanAdd(outline, pcbnew.SHAPE_POLY_SET.PM_FAST)

        return poly_set

    def generate_camouflage(self, side="F", pattern_type="swirl", scale_mm=8.0,
                            line_width_mm=0.8, pad_clearance_mm=0.4,
                            board_margin_mm=0.5, seed=42):
        """
        Main entry point to generate camouflage shapes and add them to the board.
        Returns number of shapes added.
        """
        bounds = self.get_board_bounds(margin_mm=board_margin_mm)

        # 1. Generate base camo poly set based on pattern type
        if pattern_type == "dazzle":
            camo_poly = self.generate_dazzle_polygons(bounds, scale_mm=scale_mm, seed=seed)
        elif pattern_type == "zebra":
            camo_poly = self.generate_zebra_polygons(bounds, scale_mm=scale_mm,
                                                     line_width_mm=line_width_mm, seed=seed)
        else:  # default: swirl
            camo_poly = self.generate_swirl_polygons(bounds, scale_mm=scale_mm,
                                                     line_width_mm=line_width_mm, seed=seed)

        # 2. Clip with board boundary box
        x_min, y_min, x_max, y_max = bounds
        board_box = pcbnew.SHAPE_POLY_SET()
        board_box.AddOutline(make_line_chain([
            (x_min, y_min),
            (x_max, y_min),
            (x_max, y_max),
            (x_min, y_max)
        ]))
        camo_poly.BooleanIntersection(board_box, pcbnew.SHAPE_POLY_SET.PM_FAST)

        # 3. Build pad keepout and subtract
        keepout = self.build_pad_keepout_polyset(side=side, clearance_mm=pad_clearance_mm)
        if keepout.OutlineCount() > 0:
            camo_poly.BooleanSubtract(keepout, pcbnew.SHAPE_POLY_SET.PM_FAST)

        # 4. Add resulting polygons to board as PCB_SHAPE
        target_layer = LAYER_F_SILK if side == "F" else LAYER_B_SILK
        count = 0

        # Iterate through outlines in camo_poly
        for i in range(camo_poly.OutlineCount()):
            shape = pcbnew.PCB_SHAPE(self.board)
            shape.SetShape(pcbnew.SHAPE_T_POLY)
            shape.SetLayer(target_layer)
            shape.SetFilled(True)

            # Assign single polygon outline
            single_poly = pcbnew.SHAPE_POLY_SET()
            single_poly.AddOutline(camo_poly.Outline(i))
            
            # Add corresponding holes if any
            for h in range(camo_poly.HoleCount(i)):
                single_poly.AddHole(camo_poly.Hole(i, h))

            shape.SetPolyShape(single_poly)

            # Mark with CAMO_SHAPE_MARKER
            try:
                # Use Netname or custom description field to mark our shapes
                if hasattr(shape, "SetNetname"):
                    shape.SetNetname(CAMO_SHAPE_MARKER)
                elif hasattr(shape, "SetCustomData"):
                    shape.SetCustomData(CAMO_SHAPE_MARKER)
            except Exception:
                pass

            self.board.Add(shape)
            count += 1

        pcbnew.Refresh()
        return count

    def remove_all_camo_shapes(self, side=None):
        """
        Remove all camouflage shapes generated by this plugin.
        side: 'F', 'B', or None (both)
        Returns count of removed shapes.
        """
        layers = []
        if side in ("F", None):
            layers.append(LAYER_F_SILK)
        if side in ("B", None):
            layers.append(LAYER_B_SILK)

        to_delete = []
        for drawing in self.board.GetDrawings():
            if drawing.GetLayer() in layers:
                # Check for marker
                is_camo = False
                try:
                    if hasattr(drawing, "GetNetname") and drawing.GetNetname() == CAMO_SHAPE_MARKER:
                        is_camo = True
                    elif hasattr(drawing, "GetCustomData") and drawing.GetCustomData() == CAMO_SHAPE_MARKER:
                        is_camo = True
                except Exception:
                    pass

                # Also identify by SHAPE_T_POLY on silk without text
                if not is_camo and isinstance(drawing, pcbnew.PCB_SHAPE):
                    if drawing.GetShape() == pcbnew.SHAPE_T_POLY and drawing.IsFilled():
                        try:
                            if hasattr(drawing, "GetNetname") and drawing.GetNetname() == CAMO_SHAPE_MARKER:
                                is_camo = True
                        except Exception:
                            pass

                if is_camo:
                    to_delete.append(drawing)

        for item in to_delete:
            self.board.Delete(item)

        if to_delete:
            pcbnew.Refresh()

        return len(to_delete)
